version: 2
defaults: &defaults
    working_directory: ~/repo
    docker:
        - image: circleci/node:10-jessie
jobs:
    build_win:
        <<: *defaults
        steps:
            - run: echo "Hi from $CIRCLE_JOB"
    build_linux:
        <<: *defaults
        steps:
            - run: echo "Hi from $CIRCLE_JOB"
    build_mac:
        <<: *defaults
        steps:
            - run: echo "Hi from $CIRCLE_JOB"
    demo_win:
        <<: *defaults
        steps:
            - run: echo "Hi from $CIRCLE_JOB"
    demo_linux:
        <<: *defaults
        steps:
            - run: echo "Hi from $CIRCLE_JOB"
    demo_mac:
        <<: *defaults
        steps:
            - run: echo "Hi from $CIRCLE_JOB"
    deploy:
        <<: *defaults
        steps:
            - run: echo "Hi from $CIRCLE_JOB"

workflows:
    version: 2
    demo_workdlow:
        jobs:
            - build_win
            - build_linux
            - build_mac
            - demo_win:
                requires:
                    - build_win
            - demo_linux:
                requires:
                    - build_linux
            - demo_mac:
                requires:
                    - build_mac
            - deploy:
                requires:
                    - build_win
                    - build_linux
                    - build_mac
